Feature/mg 101
sravni/mpl-meeting-service pull request #1
Opened 2021-02-15 15:14 UTC by AbrashinD

2021-02-15 15:51 UTC, mystdeim requested changes

2021-02-15 15:51 UTC, mystdeim commented on api/src/main/java/ru/sravni/mpl/meeting/api/model/meeting/Meeting.java
> +@Schema(title = "Тип встречи")
Тут наверно просто "Встреча"

2021-02-15 15:51 UTC, mystdeim commented on api/src/main/java/ru/sravni/mpl/meeting/api/model/meeting/type/CourierType.java
> +    private MeetingState state;
Эту пропертю и те, которые ниже лучше вынести в модель Meeting

2021-02-15 15:51 UTC, mystdeim commented on api/src/main/java/ru/sravni/mpl/meeting/api/model/meeting/type/CourierType.java
> +public class CourierType extends DeliveryType {
Предлагаю назвать`CourierDelivery`, всё-таки Type -- больше подходит для справочников

2021-02-15 15:51 UTC, mystdeim commented on api/src/main/java/ru/sravni/mpl/meeting/api/model/meeting/type/DeliveryType.java
> +public abstract class DeliveryType {
я бы назвал просто Delivery

2021-02-15 15:51 UTC, mystdeim commented on api/src/main/java/ru/sravni/mpl/meeting/api/model/meeting/type/OfficeType.java
> +public class OfficeType extends DeliveryType {
лучше назвать `OfficeDelivery`

2021-02-15 15:51 UTC, mystdeim commented on api/src/main/java/ru/sravni/mpl/meeting/api/model/meeting/Meeting.java
> +public class Meeting {
Предлагаю еще добавить тип MeetingType чтобы отделить курьерскую доставку от встречи в офисе.

2021-02-15 15:51 UTC, mystdeim commented on app/src/main/java/ru/sravni/mpl/meeting/persistance/entity/MeetingPE.java
> +public class MeetingPE {
нужно добавить поле MeetingType, иначе у нас не будет информации jsonb в какой тип распакоывать

2021-02-15 15:51 UTC, mystdeim commented on app/src/main/java/ru/sravni/mpl/meeting/persistance/entity/MeetingPE.java
> +    private Map<String, String> deliveryType = new HashMap<>();
я бы назвал delivery, потому что тут хранится дополнительная информация о доставке, а не просто тип

2021-02-15 15:51 UTC, mystdeim commented on app/src/main/java/ru/sravni/mpl/meeting/persistance/entity/MeetingPE.java
> +}
Давай для порядка добавим поля modified и created и хуки на обновление и создание, чтобы мы могли отлеживать когда наша модель менялась

2021-02-16 08:09 UTC, AbrashinD commented on api/src/main/java/ru/sravni/mpl/meeting/api/model/meeting/type/CourierType.java
> +    private MeetingState state;
Предлагаю в модель Meeting вынести:    
private Instant scheduleDate;

А эти поля оставить в Devivery model:
private Instant completedAt;
private Instant canceledAt;
private String meetingTimeInterval;

2021-02-16 08:12 UTC, mystdeim commented on api/src/main/java/ru/sravni/mpl/meeting/api/model/meeting/Meeting.java
> +@Schema(title = "Тип встречи")
Вот это не исправил

2021-02-16 08:13 UTC, mystdeim commented on api/src/main/java/ru/sravni/mpl/meeting/api/model/meeting/type/CourierType.java
> +    private MeetingState state;
Зачем? думаю в офисе должны быть теже самые параметры

2021-02-16 10:22 UTC, mystdeim approved these changes
LGTM

2021-02-16 11:01 UTC, merged