MG-115: Implementation CRUD and rest controller for meeting
sravni/mpl-meeting-service pull request #2
Opened 2021-02-17 07:49 UTC by AbrashinD

2021-02-17 15:49 UTC, mystdeim requested changes
Проверь тесты, у меня падают почему-то с такой ошибкой:

```
MeetingIT > update() FAILED
    org.springframework.web.client.ResourceAccessException at MeetingIT.java:192
        Caused by: java.net.ProtocolException at MeetingIT.java:192
```

2021-02-17 15:49 UTC, mystdeim commented on app/src/main/java/ru/sravni/mpl/meeting/config/OpenApiConfig.java
> +                        .version("v0.0.1"))
Предлагаю прописывать сюда версию приложения, вот пример: https://github.com/sravni/mpl-doc-service/blob/eedce7e529de6718a784ad3e22570b5118db8fc5/app/src/main/java/ru/sravni/mpl/doc/config/OpenApiConfig.java

2021-02-17 15:49 UTC, mystdeim commented on app/src/test/java/ru/sravni/mpl/meeting/MeetingIT.java
> +    @Order(1)
Если честно мне не очень нравятся вот эти аннотации. В большом проекта может быть сложно поддерживать такие тесты. Best practices говорит там вот такие вещи: "Tests should be runnable on any machine, in any order, without affecting each other. "

Оставляй как есть, но лучше стараться писать независимые изолироване тесты. В крайнем случае или если лень, можно запихать всё в один тест, который по всему бизнес флою пробежится )

2021-02-17 15:49 UTC, mystdeim commented on app/build.gradle
> +    implementation('org.apache.httpcomponents:httpclient:4.5.3')
вроде это нигде не используется...

2021-02-17 16:09 UTC, AbrashinD commented on app/build.gradle
> +    implementation('org.apache.httpcomponents:httpclient:4.5.3')
у меня только после этой депенденси заработали тесты с HttpMethod.PATCH, хотя не понятно почему

2021-02-17 16:12 UTC, mystdeim commented on app/build.gradle
> +    implementation('org.apache.httpcomponents:httpclient:4.5.3')
Хм, действительно и у меня заработали. Ну ок давай оставим её. Ток убери скобки, а то глаза режет :) давай одного стиля придерживаться

2021-02-18 07:36 UTC, mystdeim approved these changes
LGTM

2021-02-18 08:31 UTC, merged